### ISSUE TITLE
`anyjump_definition` `anyjump_reference` is not working properly

### ISSUE THREAD

**Issue by arrow2nd** [Omochice/ddu-source-anyjump#21]
Thank you for the great plugin 🙏

I tried this plugin to migrate from anyjump.vim, but it did not work properly.

## anyjump_definition

An error occurs and I cannot search.

```
[ddu] Error: undefined^@    at search (file:///Users/arrow2nd/.local/share/nvim/lazy/ddu-source-anyjump/denops/ddu-source-anyjump/definitions.ts:43:11)^@    at Object.start (file:///Users/arrow2nd/.local/share/nvim/
lazy/ddu-source-anyjump/denops/@ddu-sources/anyjump_definition.ts:37:31)^@    at eventLoopTick (ext:core/01_core.js:178:11)
```

## anyjump_reference

Incorrect search results are displayed.

![画面収録 2023-12-02 23 35 35](https://github.com/Omochice/ddu-source-anyjump/assets/44780846/9fd9c5e6-8cb3-4be2-a445-566815a71807)

## environment

- macOS Sonoma 14.1.1 (M1)
- Neovim v0.10.0
- ddu.vim (a9514dd)
- denops.vim (6c7ebef)

**Comment by Omochice** [comment]
In this scenario, it appears that DDU is being invoked from the command line. Consequently, the obtained file type corresponds to a command line environment.

I will review the pull request in detail later, but I believe the issue will likely be resolved with that fix.
